### PR TITLE
fixed Make Hero Section on the landing page responsive bug #344

### PR DESCRIPTION
**Pull request by Mr-Georgie**
## Description

Hero Section on landing page has been centered for screens smaller than 1340px while logo is hidden for screens smaller than 1340px

Fixes # 344

## Type of change

- made changes to css/custom.css file. added media query for screens smaller than 1340px
- made changes to pages/index.modules.css file. add media query for screens smaller than 1340px. Made Hero container flex with items centered

## How Has This Been Tested?

Yes. It was tested using chrome dev tools. 

## Additional Context (Please include any Screenshots/gifs if relevant)
See screenshot

mojaglobal

### CODE REVIEW

**Review by padmajabhol — CHANGES_REQUESTED** [review]
Screenshot from 2022-07-29 09-03-03
It looks like this on my browser, you can display: none the hero image for smaller devices. Please reduce the font sizes too.

**Comment by padmajabhol** [comment]
Any updates @Mr-Georgie ?

**Comment by Mr-Georgie** [comment]
on it

**Comment by Mr-Georgie** [comment]
Changes have been made to both the hero images and font sizes.

See screenshot below

open source
:

**Review by padmajabhol — CHANGES_REQUESTED** [review]
Hi @Mr-Georgie , please use yarn to install the dependencies, we aren't looking to mix the package managers here, you can find the required commands in the readme. Good to go for the rest of the changes.

**Comment by Mr-Georgie** [comment]
Hi @padmajabhol ...Very well then. I'll do so and resend PR

**Review by padmajabhol — APPROVED** [review]

**Pull request merged**
