### PR TITLE
changes made to build-size.yml for checking workflow bugs

### PR DESCRIPTION
**Pull request by Jassi10000**
# Pull Request Template

## Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
#8 
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

This is a dummy PR to check bugs in buid workflow of repo

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by sarthakkundra** [comment]
@Jassi10000 What are you not able to understand?

**Comment by Jassi10000** [comment]
> @Jassi10000 What are you not able to understand?

whenever the workflow run which have bugs, they first ask approval from maintainer , with that whenever the action runs , it doesn't show where the problem actually persists , like usually actions spot out the point where bug is there

**Comment by sohamsshah** [comment]
@Jassi10000 Is this PR currently WIP or any updates around it?

**Comment by Jassi10000** [comment]
> @Jassi10000 Is this PR currently WIP or any updates around it?

Buddy its been soo long since I have asked the repo maintainers/ contributors to help me , but I think the community is not so helpful here 
You can close this PR now

**Comment by HarshCasper** [comment]
Hi @Jassi10000 

Thanks for your contribution! 

In order to effectively help you, we would have needed a baseline implementation. Your change introduces a one-letter change that does not solve the bug at all.

Your question was also vague and we didn't understand what bug you were trying to find. You would have ideally given a shot towards understanding the file paths where the assets are present and how we can use them aptly with the GitHub Action.

In no way, it reflects how the community has been. Ever since the inception of the project, we had over 35+ contributors to the project here. A lot of contributors have been contributing far and wide, proposing new features, and fixing bugs.

We would appreciate having your contributions in the future! I am closing this PR for now.

**Pull request closed without merging**
