### PR TITLE
Fixed Issue #102

### PR DESCRIPTION
**Pull request by 17bcs1837**
## Description

I changed the CSS (background color) of the Model-Content-Wrapper(ProjectCard->card.css), so that text is visible in Roadmap section.

Fixes # (issue)

Type of Change: CSS Styling change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).

## How Has This Been Tested?
I have tested the solution on Chrome, Firefox and Edge.

Screenshot from 2021-10-05 23-08-37

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by HarshCasper** [comment]
The issue still persists in the light mode.

**Comment by 17bcs1837** [comment]
Hi @HarshCasper,
Thank you for pointing it out. I will surely look into it again.

**Comment by 17bcs1837** [comment]
@HarshCasper , Please take a look. I have resolved the issue for light mode as well.

**Review by HarshCasper — APPROVED** [review]

**Comment by HarshCasper** [comment]
@all-contributors bot please add @17bcs1837 for bug

**Pull request merged**
