### PR TITLE
Add Documentation working group in `community` section

### PR DESCRIPTION
**Pull request by asmijafar20**
- Added the Documentation working group in the `community` section of the Moja-Global community website. 
- Added the section after `Contributing Guidelines` section.

### CODE REVIEW

**Review by helper-uttam — APPROVED** [review]
LGTM 💯

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Instead of a Docs working group, make a page titled `Working group` and add DWG as one of the parts. We are constituting the CI/CD working group as well and we can expand this part then.

**Comment by sohamsshah** [comment]
Hey @asmijafar20 , are you done with reflecting the changes?

**Comment by asmijafar20** [comment]
> Hey @asmijafar20 , are you done with reflecting the changes?

yes, you may check the commits

**Comment by HarshCasper** [comment]
I have raised a follow-up PR for the `Working Groups` here #266

**Pull request closed without merging**
