### PR TITLE
improved the contributor stats view in mobile

### LINKED ISSUE #320: Feature Request: A small change in website in mobile view!
### Is your feature request related to a problem? Please describe.

Screenshot (170)

The box width need to be increased

### Describe the solution you'd like.

I would try to increase the width !

### Describe alternatives you've considered

_No response_

### Additional context.
I am participating in Gsoc this year and would love to contribute to this project

### PR DESCRIPTION
**Pull request by siddhi-244**
# Pull Request Template

## Description

I have decreased the padding in mobile view !

Fixes #320 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

just open the homepage.

## Additional Context (Please include any Screenshots/gifs if relevant)
Screenshot (173)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by siddhi-244** [comment]
@chicken-biryani  Please have a look! Thank you so much.

**Comment by chicken-biryani** [comment]
Thanks @siddhi-244.

@sohamsshah ptal!

**Comment by siddhi-244** [comment]
Any updates on this ?

**Comment by chicken-biryani** [comment]
@HarshCasper @sohamsshah can you please have a look? Thanks!

**Review by sohamsshah — APPROVED** [review]

**Comment by sohamsshah** [comment]
LGTM @siddhi-244 , thanks for contribution!

**Pull request merged**
