### PR TITLE
Dropdowns added in navbar

### PR DESCRIPTION
**Pull request by Apurba-Nath-cpu**
As proposed, 2 dropdowns contining 2 links each are added in in navbar making it look shorter and free.

# Pull Request Template

## Description

Changes are made in the docusaurus.config.js file which replaced 4 links with 2 dropdowns (each contining 2 links) on the left side of navbar. The motivation for this change was to make the navbar look more free as it looked quite congested earlier. No external dependencies  are required to merge these changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).

## How Has This Been Tested?

This has been tested in localhost:3000 using npm start in my local machine.

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by padmajabhol** [comment]
Hey @Apurba-Nath-cpu, can you sign off the DCO using these commands
git commit --amend --no-edit --signoff
git push --force-with-lease origin community_website_test_1

**Review by padmajabhol — COMMENTED** [review]
We don't really need two dropdowns, just keep one containing community, case studies and tutorials. Make sure initiative is displayed next to blog. Name the drop-down as "Know More" or something similar.

**Comment by sohamsshah** [comment]
Hey @Apurba-Nath-cpu , I see that you have raised a new PR #271 that solves #231 same as this one. Closing this PR since it is duplicated.

**Comment by Apurba-Nath-cpu** [comment]
Yes, I was told to raise a new PR as I messed up the older one with lots of
commits.

**Pull request closed without merging**
