### PR TITLE
UI Improvement: Revamp Community Initiatives and Get Involved Sections

### LINKED ISSUE #237: Bug:  ALIGNMENT IN INITIATIVES SECTION
### Describe the bug.

The alignment of cards in the  /initiatives , looks a bit absurb , to be precise , Google Summer of Docs Card is a bit misaligned . 

### Describe the steps to reproduce the behavior.

Open the /initiatives Page on the community website .

### Expected behavior.

All the cards should be aligned properly , this could be done by shifting the button to bottom , aligned with other buttons .

### Screenshots.

image

### Operating Environment

Windows 10 , Firebox 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AayushSaini101**
# Pull Request Template

## Description
Resolved ALIGNMENT IN INITIATIVES SECTION and images are added(Locally Stored) for better UI

Fixes #237 

## Previous UI:

new

## New UI
new

-  Bugfix (non-breaking change which fixes an issue).
-  New feature (non-breaking change which adds functionality).

### CODE REVIEW

**Comment by AayushSaini101** [comment]
@sohamsshah  Please review it

**Comment by sohamsshah** [comment]
Hey @AayushSaini101 , your branch `Main2` is behind the latest branch. Also, there are a lot of changes visible that aren't related to this issue. Please make the branch up-to-date and should make only the visible changes shown up, whilst others shall be considered of the main branch only (resolve merge conflicts if any).

**Comment by AayushSaini101** [comment]
@sohamsshah  Okay, I will update the branch

**Review by sohamsshah — APPROVED** [review]
Thanks @AayushSaini101 for working on this. I have added few UI updates on top of your contributions. LGTM! 🚀

**Comment by sohamsshah** [comment]
Latest UI:
Community Initiatives Section
image

Get Involved
image

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
