### PR TITLE
added issue forms  for the Issue Templates

### LINKED ISSUE #58: Adding Issue Forms for Issue Templates
Using the [Issue Forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) for the Issue Templates which is configured in YAML format and eliminates the markdown templates.
It will enable the members to create a structured form with required inputs and fields.

### PR DESCRIPTION
**Pull request by rutujaingole**
# Pull Request Template

## Description
Added Issue Forms for the Issue Templates

Fixes #58 

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update.

## How Has This Been Tested?
  ___

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [✓ ] My code follows the style guidelines of this project.
- [✓] I have performed a self-review of my own code.
- [✓] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [✓ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by rutujaingole** [comment]
@HarshCasper  I've added the Issue forms, please review these!

**Review by Siddhant-K-code — APPROVED** [review]
LGTM! 🎉 

Thanks

**Comment by sarthakkundra** [comment]
Is there a corresponding issue for this? Can someone please link it? 
@rutujaingole @Siddhant-K-code

**Comment by rutujaingole** [comment]
> Is there a corresponding issue for this? Can someone please link it?
> @rutujaingole @Siddhant-K-code

@sarthakkundra Issue for this PR is now linked.

**Comment by HarshCasper** [comment]
Closing this in favor of #71

**Pull request closed without merging**
