### PR TITLE
Update: favicon with moja-global logo

### LINKED ISSUE #42: fix: Update favicon
## Description

Replace Docusaurus favicon with moja global favicon. We can use this favicon [https://github.com/moja-global/FLINT-UI/blob/master/flint.ui/public/favicon.ico](https://github.com/moja-global/FLINT-UI/blob/master/flint.ui/public/favicon.ico).

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
# Pull Request Template

## Description

Updated the Favicon Logo in the title bar with a logo of moja-global

Fixes #42 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).

## How Has This Been Tested?

Just Check the title bar in any of the browsers

## Additional Context
image

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by aornugent** [comment]
Hi @Siddhant-K-code - sorry to be pedantic, but can we please switch to the dark green logo in #50? These are the primary brand colours.

**Comment by Siddhant-K-code** [comment]
In #43 right? Because this issue will be fixed by #43.

**Comment by Siddhant-K-code** [comment]
> Hi @Siddhant-K-code - sorry to be pedantic, but can we please switch to the dark green logo in #50? These are the primary brand colours. 

@aornugent 
In #43 right? Because this issue will be fixed by #43.

**Comment by sarthakkundra** [comment]
LGTM!

**Pull request merged**
