### PR TITLE
a sticky navbar is better for navigation imo

### PR DESCRIPTION
**Pull request by aryabyte21**
Issue: The navbar used to hide on the community website whenever I scrolled down. I found it counter productive for navigating the website so I suggest that we keep the navbar sticky. 
Signed-off-by: Arya Bhosale <arya2001bhosale@gmail.com>
@chicken-biryani  what do you think?

### CODE REVIEW

**Comment by chicken-biryani** [comment]
@sohamsshah what do you think?

**Comment by padmajabhol** [comment]
Earlier we were planning to have a "back-to-top" button but we can also have a sticky navbar for the time being.

**Comment by AryaArunB** [comment]
@padmajabhol @chicken-biryani even the translate button isn't working wherein it is supposed to translate the page to spanish ig. So shall we completely remove that option from the nav bar or we shall provide some good translation and maybe also add translation in hindi.

**Comment by chicken-biryani** [comment]
@AryaArunB I think we can add translations. In a diff PR ofc. I believe we didn't have the content. Let's stick to ths languages that are already there for now.

**Comment by AryaArunB** [comment]
Okay sure! So you mean we will be doing Spanish right? I went through the [Docusaurus](https://docusaurus.io/) documentation and over there we will have to use hard written text instead of react elements to use the Translate API.

**Comment by chicken-biryani** [comment]
@AryaArunB I am not sure. I think a better candidate for the same may be someone who already knows Spanish?

@HarshCasper @padmajabhol what's your opinion on the same?

**Comment by padmajabhol** [comment]
> @AryaArunB I am not sure. I think a better candidate for the same may be someone who already knows Spanish?
> 
> @HarshCasper @padmajabhol what's your opinion on the same?

I believe it could be safe to go with someone who has a good command of the language.

**Pull request closed without merging**
