### PR TITLE
Create a Team Page of all contributors of The Moja Global.

### PR DESCRIPTION
**Pull request by asmijafar20**
- Created the Team page `team.js` in the [https://github.com/moja-global/community-website/tree/main/website/src/pages](url) which display the data from the JSON file.
- The data is pulled from the `all-contributors-data.json` file in the `TeamCard` folder. 
- The `teamcard.js` file in the TeamCard folder fetch all the data from the JSON file.
- This page is to Thank everyone involved in contributing to `The Moja Global`.

### CODE REVIEW

**Comment by sohamsshah** [comment]
Hey @asmijafar20 , are you working on it?

**Comment by asmijafar20** [comment]
> Hey @asmijafar20 , are you working on it?

Yea I'm trying to rewrite the CSS files.

**Comment by sohamsshah** [comment]
> > Hey @asmijafar20 , are you working on it?
> 
> Yea I'm trying to rewrite the CSS files.

Okay, great. Please let me know if you face any blockers.

**Comment by asmijafar20** [comment]
> Hey @asmijafar20 , are you working on it?

Yea I'm trying to rewrite the CSS files. 

> > > Hey @asmijafar20 , are you working on it?
> > 
> > 
> > Yea I'm trying to rewrite the CSS files.
> 
> Okay, great. Please let me know if you face any blockers.

Sure.

**Comment by asmijafar20** [comment]
I have updated the new pull request regarding the same issue.

**Comment by sohamsshah** [comment]
> I have updated the new pull request regarding the same issue.

I cannot find the PR. If you have solved the issue, feel free to raise a PR :))

**Comment by asmijafar20** [comment]
> > I have updated the new pull request regarding the same issue.
> 
> I cannot find the PR. If you have solved the issue, feel free to raise a PR :))



> > I have updated the new pull request regarding the same issue.
> 
> I cannot find the PR. If you have solved the issue, feel free to raise a PR :))

Here it is: https://github.com/moja-global/community-website/pull/210. Please review it. Thanks :)

**Pull request closed without merging**
