### PR TITLE
Fixes sitemap config; Adds robots.txt

### LINKED ISSUE #72: Fix `sitemap.xml` and add `robots.txt` on the community website
## Description

Currently, our `sitemap.xml` isn't behaving as expected: https://community.moja.global/sitemap.xml

We would ideally like to fix this error. We would also like to add the `robots.txt` by referencing the agents that can crawl the website. Refer [this](https://github.com/facebook/docusaurus/discussions/4033).

### PR DESCRIPTION
**Pull request by eemike07**
# Pull Request Template

## Description
Fixes sitemap by updating `docusaurus.config.js`.  
Adds `robots.txt` to `static` folder

Since we already have `@docusaurus/preset-classic` installed, we don't need to install `@docusaurus/plugin-sitemap`.  
`@docusaurus/plugin-sitemap` can be configured through `classic preset options`.  
See: https://docusaurus.io/docs/presets#docusauruspreset-classic

Fixes #72 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).

## How Has This Been Tested?

Honestly, I don't have a real way of testing this until it is fully deployed.

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by eemike07** [comment]
hmm....I ran `git commit --amend --no-edit --signoff` and pushed it.  Should trigger another build?

**Comment by HarshCasper** [comment]
> hmm....I ran `git commit --amend --no-edit --signoff` and pushed it. Should trigger another build?

Run these: 

```sh
git commit --amend --no-edit --signoff
git push --force-with-lease origin fixes-sitemap
```

This will do the trick. Thanks!

**Review by HarshCasper — APPROVED** [review]
Please sign off the DCO and this would be good to merge! 

Thanks a lot for your quick patch :tada:

**Comment by eemike07** [comment]
> > hmm....I ran `git commit --amend --no-edit --signoff` and pushed it. Should trigger another build?
> 
> Run these:
> 
> ```shell
> git commit --amend --no-edit --signoff
> git push --force-with-lease origin fixes-sitemap
> ```
> 
> This will do the trick. Thanks!

I did run those....but I think its failing because of the Merge Request itself not being signed  :(  I can create a new branch and re-push

**Comment by eemike07** [comment]
Closing.  See: https://github.com/moja-global/community-website/pull/79

**Pull request closed without merging**
