### PR TITLE
Issue #351 Rewamping know the community section Adding Slider to the Cards

### LINKED ISSUE #351: Feature Request: revamp "Know the community" section
### Describe the solution you'd like.

We are changing the current "Know the community" section of our website.
Please refer to the below image for the reference.

MacBook Pro 14_ - 2

If are interested to work on this, we might additionally want you to attend our community meetings.
Its recommended that you accomplish this in multiple commits, and open a PR right after the first one.

### PR DESCRIPTION
**Pull request by harshilhuda**
Signed-off-by: harshilhuda <harshilhuda@gmail.com>

Added the slider to the cards, added new component CommunitySlider in src/components added the left and right icons using dependency react-icons-md all the required css added in custom.css in src/css/custom.css

Fixes #351  

Changes the layout of know the community section to a better looking slider.
This may not be the final look. Would like to here suggestions if any and will implement it.

Screenshot (21)
Screenshot (20)

### CODE REVIEW

**Comment by harshilhuda** [comment]
@padmajabhol anything more i should add?

**Comment by padmajabhol** [comment]
> @padmajabhol anything more i should add?

I don't think it looks similar to the prototype we had. Do you need some time to work on this?

**Comment by harshilhuda** [comment]
> > @padmajabhol anything more i should add?
> 
> I don't think it looks similar to the prototype we had. Do you need some time to work on this?

Okay I will work on it to make it look similar to the prototype👍

**Comment by harshilhuda** [comment]
Screenshot (22)
@padmajabhol does this look okay? Please do check the preview and tell any changes that are to be made.

**Comment by padmajabhol** [comment]
> Screenshot (22) @padmajabhol does this look okay? Please do check the preview and tell any changes that are to be made.

I don't think we proposed this in the design, can you modify it to look exactly as what we have in figma?

**Pull request closed without merging**
