### PR TITLE
Contributing guidelines added.

### LINKED ISSUE #308: Documentation: Contributor guidelines
### What is the current documentation state?

Dont have a contributor guidelines of MOJA-GLOBAL

### Where is this stated?

_No response_

### Why do you want to improve the statement?

_No response_

### Proposed Statement

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by Ash-KODES**
# Pull Request Template

## Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #308 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by ShadyResurrected** [comment]
Hi, I am Chandradeep Chandra, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by Ash-KODES** [comment]
> Hi, I am Chandradeep Chandra, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

Issue had already been resolved,you can contribute to other ones:)

**Comment by anushkachauhxn** [comment]
> @anushkachauhxn please review

I think it looks good! But I'm not one of the moderators here and I'm a little confused why I was tagged here. 😅

**Comment by Ash-KODES** [comment]
> > @anushkachauhxn please review
> 
> I think it looks good! 👍 But I'm not one of the moderators here and I'm a little confused why I was tagged here. 😅

I saw your name somewhere in the readme,,,so i thought you are moderator,,,,apologies:)

**Comment by Ash-KODES** [comment]
@HarshCasper  Please review

**Comment by Ash-KODES** [comment]
> Contributing guidelines are already available here: https://github.com/moja-global/community-website/blob/main/CONTRIBUTING.md
> 
> What is the intended to be fixed?

I wanted to add a section of contributing guidelines in readme,,if not required you can definetly close the issue.

**Pull request closed without merging**
