### PR TITLE
Blog: How AFOLU sector responsible for GHG emission and removal

### LINKED ISSUE #251: Blog: How AFOLU sector responsible for GFG emission and removal
### Is your feature request related to a problem? Please describe.

Most of the contributors may want to understand FLINT and moja-global but got confused due to less understanding about sources  of GFG.

### Describe the solution you'd like.

I want to write a blog explaining how AFOLU sector is also major source of gfg emission.

### Describe alternatives you've considered

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by Sukriti-sood**
Fixes #251

### CODE REVIEW

**Comment by Sukriti-sood** [comment]
@HarshCasper Please review this.

**Comment by aornugent** [comment]
Hi @Sukriti-sood - sorry for the slow response here. The content looks great thank you. 

@Namyalg could you please review against our style guidelines? Otherwise I think it's good to go!

**Review by aornugent — APPROVED** [review]

**Review by Namyalg — APPROVED** [review]
LGTM!

**Review by padmajabhol — APPROVED** [review]
Thanks a lot @Sukriti-sood 🚀

**Pull request merged**
