### PR TITLE
docs: Added OSD 2022 Recap Blog describing Moja Global's involvement in OSD 2022

### LINKED ISSUE #415: Adding a blog about Moja Global's involvement in Open Source Day 2022
### What is the current documentation state?

# Description

As discussed earlier, I would like to add an 'OSD 2022 Recap' blog regarding Moja Global's involvement in Open Source Day 2022.

### Where is this stated?

_No response_

### Why do you want to improve the statement?

_No response_

### Proposed Statement

_No response_

### Additional context.

@HarshCasper I know this task has been pending since a long time, so I'd like to work on this!

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
Signed-off-by: Abhilipsa Sahoo <abhilipsasahoo03@outlook.com>

# Pull Request Template

## Description
- Added OSD 2022 Recap Blog describing Moja Global's involvement in OSD 2022

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #415 

## Type of change

Please delete options that are not relevant.

- [X] This change requires a documentation update.

## Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have made corresponding changes to the documentation.

- [X] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
@HarshCasper @chicken-biryani kindly take a look!

**Comment by chicken-biryani** [comment]
@abhilipsasahoo03 freat initiative. Thank you for sticking around so far.

Thoughts:-
1) The blog's wordings are really good. Very mature amd well written.
2) Although it's written VERY well... The thing is... I think we can add a little bit of human touch on it? To make it sound more welcoming? It would be like a plain sponge cake vs a sponge cake with sprinkles. Don't know if that makes sense.
3) Just cross check the projects once.

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 freat initiative. Thank you for sticking around so far.
> 
> Thoughts:-
> 1) The blog's wordings are really good. Very mature amd well written.
> 2) Although it's written VERY well... The thing is... I think we can add a little bit of human touch on it? To make it sound more welcoming? It would be like a plain sponge cake vs a sponge cake with sprinkles. Don't know if that makes sense.
> 3) Just cross check the projects once.

About the point (2), I totally get your point! I'll work on it. About (3), Should I add link to the projects as well, or it won't be necessary? Also, about the cross-checking part, I referred to the emails and the messages in the OSD slack channel to confirm that these were the two projects selected. :)

**Comment by abhilipsasahoo03** [comment]
@chicken-biryani @HarshCasper I have made the required changes, kindly review. :)

**Comment by abhilipsasahoo03** [comment]
Hi @HarshCasper please take a look

**Comment by abhilipsasahoo03** [comment]
Hi @HarshCasper @Palaksharma23 please take a look!

**Review by Palaksharma23 — APPROVED** [review]
Nice work @abhilipsasahoo03, Looks good to me :)

**Pull request closed without merging**
