### PR TITLE
Fixes sitemap config; Adds robots.txt

### LINKED ISSUE #72: Fix `sitemap.xml` and add `robots.txt` on the community website
## Description

Currently, our `sitemap.xml` isn't behaving as expected: https://community.moja.global/sitemap.xml

We would ideally like to fix this error. We would also like to add the `robots.txt` by referencing the agents that can crawl the website. Refer [this](https://github.com/facebook/docusaurus/discussions/4033).

### PR DESCRIPTION
**Pull request by eemike07**
Signed-off-by: Maku <eemike07@gmail.com>

# Pull Request Template

## Description
Fixes sitemap by updating `docusaurus.config.js`.  
Adds `robots.txt` to `static` folder

Since we already have `@docusaurus/preset-classic` installed, we don't need to install `@docusaurus/plugin-sitemap`.  
`@docusaurus/plugin-sitemap` can be configured through `classic preset options`.  
See: https://docusaurus.io/docs/presets#docusauruspreset-classic

Fixes #72 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).

## How Has This Been Tested?

Honestly, I don't have a real way of testing this until it is fully deployed.

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by eemike07** [comment]
If this meets acceptance criteria and gets merged, could you add the `label: hacktoberfest-accepted`?
:) Greatly appreciate it!  For some reason Hacktoberfest is showing this issue as "Project not participating"

**Review by HarshCasper — APPROVED** [review]

**Comment by HarshCasper** [comment]
Hi @eemike07 

Can you please have a look and see if your PR counts in Hacktoberfest?

**Comment by eemike07** [comment]
For some reason it still states "Project not participating"

**Comment by HarshCasper** [comment]
> For some reason it still states "Project not participating".
> 
> Might have to add the `hacktoberfest-accepted` tag to the issue rather than the Pull Request. #72 Also curious if tags are case-sensitive `Hacktoberfest` vs. `hacktoberfest`

I have pinged the Hacktoberfest organizers on the Discord channel. I would be awaiting their response and keep you posted about the same. In the meantime, I discovered that a lot of projects are facing the same issue due to queries not being executed successfully. We will have a fix for this very soon. Thanks for your contribution and patience once again!

**Comment by eemike07** [comment]
No problem!  Thanks for allowing me to participate and to contribute :) I've been having fun so far!

**Comment by eemike07** [comment]
Looks like it kicked in! "Matures in 14 days"

**Comment by HarshCasper** [comment]
That sounds cool! Please let us know if you wish to take up another issue. We would love to have you contribute :)

**Comment by HarshCasper** [comment]
@all-contributors bot please add @eemike07 for code

**Pull request merged**
