### PR TITLE
Updated margin of links in header section

### PR DESCRIPTION
**Pull request by utkarsh1311**
# Pull Request Template

## Description
I have updated the margin of links in the ```hero``` div of the header section.

Fixes # (issue)
#100 
## Type of change
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).

## Additional Context (Please include any Screenshots/gifs if relevant)
The updated links look like this - 
Screenshot from 2021-10-05 19-28-42

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Review by HarshCasper — APPROVED** [review]
LGTM! Thanks.

**Comment by utkarsh1311** [comment]
Hey can you add the ```hacktoberfest-accepted``` label to this PR.

**Comment by HarshCasper** [comment]
@all-contributors bot please add @utkarsh1311 for bug

**Comment by utkarsh1311** [comment]
Thank you for adding me as a contributor 😊

**Pull request merged**
